[package]
name = "demo4_backend"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
boa_engine = "0.19.0"
candid = "0.8"
ic-cdk = "0.15.0"
ic-wasi-polyfill = "0.6"




